- name: Deploy manifests in k8s cluster
  hosts: localhost
  tasks: 
    - name: Install docker python module
      pip:
        name: docker
        state: present
    #- name: Login to docker locally to create .dockerjson config file
    #  docker_login:
    #    registry_url: https://index.docker.io/v1/
    #    username: "{{ docker_user }}"
    #    password: "{{ docker_pass }}"
      
    - name: Create docker registry secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: my-registry-key
            namespace: default
          data:
            .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json' ) | b64encode }}"
    
    - name: Add ingress-nginx Helm repo
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      args:
        creates: /root/.cache/helm/repository/ingress-nginx-index.yaml  # Optional, to avoid repeated adding

    - name: Update Helm repo
      command: helm repo update



    - name: Deploy nginx ingress controller
      kubernetes.core.helm:
        name: ingress-controller
        release_namespace: ingress
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx
        
    - name: Deploy all k8s manifests
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '{{ item }}') }}"
        state: present
        namespace: default
      with_fileglob:
        - "kubernetes-manifests/exercise-7/*.yaml"