- name: Deploy manifests in k8s cluster
  hosts: localhost
  tasks: 
    - name: Install docker python module
      pip:
        name: docker
        state: present
  
    - name: Deploy nginx ingress controller
      kubernetes.core.helm:
        name: ingress-controller
        release_namespace: ingress
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx
    - name: Deploy Mysql chart with 3 replicas
      kubernetes.core.helm:
        name: mysql-release
        chart_ref: bitnami/mysql
        release_namespace: default
        # you can set one of minikube, LKE or EKS chart values file from exercise-8 directory
        values: "{{ lookup('template', 'kubernetes-manifests/exercise-8/mysql-chart-values-minikube.yaml') | from_yaml }}"
    - name: Deploy Java application manifests
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '{{ item }}') }}"
        state: present
        namespace: default
      with_fileglob:
        - "kubernetes-manifests/exercise-8/java-*.yaml"